# Generated by Django 4.2.9 on 2024-02-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_data_joined_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
