# Generated by Django 4.2.9 on 2024-02-20 19:02

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_creator_remove_user_updated_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='user_id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
