# Generated by Django 4.2.9 on 2024-02-28 01:51

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_creator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='creator', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
