# Generated by Django 4.2.9 on 2024-03-02 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
    ]
