# Generated by Django 4.2.9 on 2024-03-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.creator', verbose_name='creator'),
        ),
    ]
