# Generated by Django 4.2.9 on 2024-03-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_remove_administrator_creator_and_more'),
        ('user', '0014_alter_user_creator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creator_user',
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
