# Generated by Django 4.2.9 on 2024-03-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email', 'username', 'nickname'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
