# Generated by Django 4.2.9 on 2024-03-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
