# Generated by Django 4.2.9 on 2024-02-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfsatisfactionlevel',
            name='self satisfaction level icon',
        ),
        migrations.AddField(
            model_name='selfsatisfactionlevel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='self satisfaction level icon'),
        ),
    ]
