# Generated by Django 4.2.9 on 2024-02-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0004_alter_selfsatisfactionlevel_self_satisfaction_level_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfsatisfactionlevel',
            old_name='self satisfaction level icon',
            new_name='icon_link',
        ),
    ]
