# Generated by Django 4.2.9 on 2024-02-22 21:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0005_rename_self_satisfaction_level_icon_selfsatisfactionlevel_icon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsatisfactionlevel',
            name='icon_link',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[50, 50], upload_to='api/self_satisfaction_level/img/thumbnail/', verbose_name='self satisfaction level icon'),
        ),
    ]
