# Generated by Django 4.2.9 on 2024-02-23 00:42

import apps.api.self_satisfaction_level.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0007_alter_selfsatisfactionlevel_icon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfsatisfactionlevel',
            name='test_pillow_icon_link',
            field=models.ImageField(blank=True, null=True, upload_to='pillow_library_test/', verbose_name='self satisfaction level icon'),
        ),
        migrations.AlterField(
            model_name='selfsatisfactionlevel',
            name='icon_link',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[150, 150], upload_to=apps.api.self_satisfaction_level.models.get_image_file_name, verbose_name='self satisfaction level icon'),
        ),
    ]
