# Generated by Django 4.2.9 on 2024-02-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0011_remove_selfsatisfactionlevel_test_pillow_icon_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfsatisfactionlevel',
            name='test_pillow_icon_link',
            field=models.ImageField(blank=True, null=True, upload_to='pillow_library_test/', verbose_name='Test Pillow Library'),
        ),
    ]
