# Generated by Django 4.2.9 on 2024-03-24 20:38

import apps.api.self_satisfaction_level.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_satisfaction_level', '0015_alter_selfsatisfactionlevel_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsatisfactionlevel',
            name='value',
            field=models.SmallIntegerField(unique=True, validators=[apps.api.self_satisfaction_level.validators.validate_satisfaction_level_value], verbose_name='self satisfaction level value'),
        ),
    ]
