# Generated by Django 4.2.9 on 2024-02-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_level', '0002_emotionallevel_test_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionallevel',
            name='test_image_field',
        ),
    ]
