# Generated by Django 4.2.9 on 2024-03-24 20:38

import apps.api.emotional_level.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotional_level', '0006_alter_emotionallevel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionallevel',
            name='value',
            field=models.SmallIntegerField(unique=True, validators=[apps.api.emotional_level.validators.validate_emotional_level_value], verbose_name='emotional level value'),
        ),
    ]
