# Generated by Django 4.2.9 on 2024-03-12 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_alter_client_thumbnail_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to='client.client', verbose_name='client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'group - Client',
                'verbose_name_plural': 'groups - Clients',
                'ordering': ['training_group_id', 'client_id'],
            },
        ),
    ]
