# Generated by Django 4.2.9 on 2024-03-11 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_group', '0004_alter_traininggroup_administrator_and_more'),
        ('client', '0006_alter_client_thumbnail_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training_group.traininggroup', verbose_name='training group')),
            ],
            options={
                'verbose_name': 'group - client',
                'verbose_name_plural': 'groups - clients',
                'ordering': ['client', 'training_group'],
                'unique_together': {('training_group', 'client')},
            },
        ),
    ]
