# Generated by Django 4.2.9 on 2024-03-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_group', '0005_alter_traininggroup_client'),
        ('client', '0006_alter_client_thumbnail_link'),
        ('group_many_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmanyclient',
            options={'ordering': ['client_many', 'training_group_many'], 'verbose_name': 'group - client', 'verbose_name_plural': 'groups - clients'},
        ),
        migrations.RenameField(
            model_name='groupmanyclient',
            old_name='client',
            new_name='client_many',
        ),
        migrations.RenameField(
            model_name='groupmanyclient',
            old_name='training_group',
            new_name='training_group_many',
        ),
        migrations.AlterUniqueTogether(
            name='groupmanyclient',
            unique_together={('training_group_many', 'client_many')},
        ),
    ]
