# Generated by Django 4.2.9 on 2024-03-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_group', '0001_initial'),
        ('group_many_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmanyclient',
            name='training_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to='training_group.traininggroup', verbose_name='training group'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmanyclient',
            unique_together={('training_group_id', 'client_id')},
        ),
    ]
