# Generated by Django 4.2.9 on 2024-03-12 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_group', '0009_alter_traininggroup_training_year'),
        ('client', '0006_alter_client_thumbnail_link'),
        ('group_many_client', '0002_alter_groupmanyclient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmanyclient',
            options={'ordering': ['training_group_many', 'client_many'], 'verbose_name': 'group - client', 'verbose_name_plural': 'groups - clients'},
        ),
        migrations.AlterField(
            model_name='groupmanyclient',
            name='client_many',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to='client.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='groupmanyclient',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='groupmanyclient',
            name='training_group_many',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_many_client', to='training_group.traininggroup', verbose_name='training group'),
        ),
    ]
