# Generated by Django 4.2.9 on 2024-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientstatus',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='client status'),
        ),
    ]
