# Generated by Django 4.2.9 on 2024-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ['name'], 'verbose_name': 'payment type', 'verbose_name_plural': 'payment types'},
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='payment type'),
        ),
    ]
