# Generated by Django 4.2.9 on 2024-03-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_document', '0001_initial'),
        ('payment_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_group', '0004_alter_traininggroup_administrator_and_more'),
        ('client', '0006_alter_client_thumbnail_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroupClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField(blank=True, null=True, verbose_name='Client payment amount')),
                ('refund_amount', models.FloatField(blank=True, null=True, verbose_name='Client payment refund')),
                ('payment_date', models.DateField(verbose_name='Client payment date')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_client_payment', to='client.client', verbose_name='client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_client_payment', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('payment_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_client_payment', to='payment_document.paymentdocument', verbose_name='Payment document')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_client_payment', to='payment_type.paymenttype', verbose_name='Payment type')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group_client_payment', to='training_group.traininggroup', verbose_name='training group')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['payment_date'],
            },
        ),
    ]
