# Generated by Django 4.2.9 on 2024-03-12 01:46

import apps.api.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_client_payment', '0003_alter_groupclientpayment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclientpayment',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='Payment amount'),
        ),
        migrations.AlterField(
            model_name='groupclientpayment',
            name='refund_amount',
            field=models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='Payment refund'),
        ),
    ]
