# Generated by Django 4.2.9 on 2024-02-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='company.company', verbose_name='department company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='department'),
        ),
    ]
