# Generated by Django 4.2.9 on 2024-02-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_department_company_id_department_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='administrator_id',
            new_name='administrator',
        ),
    ]
