# Generated by Django 4.2.9 on 2024-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_department_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='note'),
        ),
    ]
