# Generated by Django 4.2.9 on 2024-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_department_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='department name'),
        ),
    ]
