# Generated by Django 4.2.9 on 2024-03-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_department_address_alter_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['company', 'administrator', 'name', 'address', 'is_active', 'created_at', 'updated_at', 'creator'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
