# Generated by Django 4.2.9 on 2024-03-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
