# Generated by Django 4.2.9 on 2024-03-07 12:10

import apps.api.administrator.utils
import apps.api.administrator.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_status', '0003_alter_clientstatus_creator'),
        ('gender', '0003_alter_gender_creator'),
        ('country', '0004_alter_country_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_link', models.ImageField(blank=True, null=True, upload_to=apps.api.administrator.utils.get_image_file_name, validators=[apps.api.administrator.validators.validate_image_size], verbose_name='avatar thumbnail link')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('address', models.TextField(max_length=500, verbose_name='address')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('bibliography', models.TextField(blank=True, max_length=500, null=True, verbose_name='bibliography')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('client_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='client creator')),
                ('client_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='client_status.clientstatus', verbose_name='client status')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='country.country', verbose_name='country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='gender.gender', verbose_name='client gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['user__email', 'user__username', 'user__nickname'],
            },
        ),
    ]
