# Generated by Django 4.2.9 on 2024-03-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
