# Generated by Django 4.2.9 on 2024-03-07 14:37

import apps.api.administrator.validators
import apps.api.client.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_alter_gender_creator'),
        ('client_status', '0003_alter_clientstatus_creator'),
        ('country', '0004_alter_country_creator'),
        ('client', '0003_remove_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='client_status.clientstatus', verbose_name='client status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='country.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='gender.gender', verbose_name='client gender'),
        ),
        migrations.AlterField(
            model_name='client',
            name='thumbnail_link',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.client.utils.get_image_file_name, validators=[apps.api.administrator.validators.validate_image_size], verbose_name='avatar thumbnail link'),
        ),
    ]
