# Generated by Django 4.2.9 on 2024-03-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_alter_gender_options_alter_gender_name'),
        ('client', '0004_alter_client_address_alter_client_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='gender.gender', verbose_name='Gender'),
        ),
    ]
