# Generated by Django 4.2.9 on 2024-03-08 00:22

import apps.api.client.utils
import apps.api.client.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='thumbnail_link',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.client.utils.get_image_file_name, validators=[apps.api.client.validators.validate_image_size], verbose_name='avatar thumbnail link'),
        ),
    ]
