# Generated by Django 4.2.9 on 2024-03-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_year', '0002_alter_trainingyear_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingyear',
            options={'ordering': ['name'], 'verbose_name': 'training year (period)', 'verbose_name_plural': 'training years (periods)'},
        ),
        migrations.AlterField(
            model_name='trainingyear',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='training year number (period name)'),
        ),
    ]
