# Generated by Django 4.2.9 on 2024-03-12 01:30

import apps.api.utils.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotional_level', '0005_alter_emotionallevel_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_many_client', '0002_alter_groupmanyclient_options_and_more'),
        ('self_satisfaction_level', '0015_alter_selfsatisfactionlevel_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClientProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_completed', models.BooleanField(default=False, verbose_name='task completed')),
                ('check_point_date', models.DateField(unique_for_date=True, verbose_name='check point date')),
                ('current_weight', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current weight')),
                ('current_breast', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current breast')),
                ('current_shoulders', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current shoulders')),
                ('current_waist', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current weight')),
                ('current_hips', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current hips')),
                ('current_height', models.FloatField(blank=True, null=True, validators=[apps.api.utils.utils.number_or_str_to_abs_float], verbose_name='current height')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='description')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_client_progress', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('emotional_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_client_progress', to='emotional_level.emotionallevel', verbose_name='emotional level')),
                ('self_satisfaction_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_client_progress', to='self_satisfaction_level.selfsatisfactionlevel', verbose_name='self satisfaction level')),
                ('training_group_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_client_progress', to='group_many_client.groupmanyclient', verbose_name='group - client')),
            ],
            options={
                'verbose_name': 'group-client-progress',
                'verbose_name_plural': 'group-client-progress',
                'ordering': ['check_point_date'],
            },
        ),
    ]
