# Generated by Django 4.2.9 on 2024-03-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_many_client', '0002_initial'),
        ('group_client_progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupclientprogress',
            old_name='group_client_id',
            new_name='group_many_client',
        ),
        migrations.AlterUniqueTogether(
            name='groupclientprogress',
            unique_together={('check_point_date', 'group_many_client')},
        ),
    ]
