# Generated by Django 4.2.9 on 2024-03-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_many_client', '0003_alter_groupmanyclient_creator'),
        ('group_client_progress', '0002_rename_group_client_id_groupclientprogress_group_many_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupclientprogress',
            options={'ordering': ['-check_point_date', 'group_many_client'], 'verbose_name': 'group - Client - Progress', 'verbose_name_plural': 'groups - Clients - Progresses'},
        ),
        migrations.AlterUniqueTogether(
            name='groupclientprogress',
            unique_together={('group_many_client', 'check_point_date')},
        ),
    ]
