# Generated by Django 4.2.9 on 2024-03-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininggroup',
            options={'ordering': ['training_group_code', 'training_group_name'], 'verbose_name': 'training group', 'verbose_name_plural': 'training groups'},
        ),
    ]
