# Generated by Django 4.2.9 on 2024-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        ('client', '0006_alter_client_thumbnail_link'),
        ('training_group', '0002_alter_traininggroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='client',
            field=models.ManyToManyField(related_name='training_group', to='client.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='coach',
            field=models.ManyToManyField(related_name='training_group', to='coach.coach', verbose_name='coach'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='training_group_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='training group code'),
        ),
        migrations.AlterField(
            model_name='traininggroup',
            name='training_group_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='training group name'),
        ),
    ]
