# Generated by Django 4.2.9 on 2024-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_many_client', '0002_alter_groupmanyclient_options_and_more'),
        ('client', '0006_alter_client_thumbnail_link'),
        ('training_group', '0007_alter_traininggroup_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traininggroup',
            name='client',
        ),
    ]


    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='training_group', through='group_many_client.GroupManyClient', to='client.client', verbose_name='client'),
        ),
    ]
