# Generated by Django 4.2.9 on 2024-03-12 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_year', '0003_alter_trainingyear_options_alter_trainingyear_name'),
        ('training_group', '0008_alter_traininggroup_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggroup',
            name='training_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_group', to='training_year.trainingyear', verbose_name='training year (period)'),
        ),
    ]
