# Generated by Django 4.2.9 on 2024-02-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_administrator_thumbnail_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='bibliography',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='bibliography'),
        ),
    ]
