# Generated by Django 4.2.9 on 2024-02-26 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_creator_id'),
        ('administrator', '0004_administrator_created_at_administrator_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.creator', verbose_name='creator'),
            preserve_default=False,
        ),
    ]
