# Generated by Django 4.2.9 on 2024-02-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_administrator_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['user__nickname'], 'verbose_name': 'administrator', 'verbose_name_plural': 'administrators'},
        ),
    ]
