# Generated by Django 4.2.9 on 2024-02-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['user__email', 'user__username', 'user__nickname'], 'verbose_name': 'administrator', 'verbose_name_plural': 'administrators'},
        ),
    ]
