# Generated by Django 4.2.9 on 2024-02-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_creator_id'),
        ('administrator', '0007_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='user.creator', verbose_name='creator'),
        ),
    ]
