# Generated by Django 4.2.9 on 2024-03-01 16:41

import apps.api.administrator.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_administrator_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='thumbnail_link',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.administrator.utils.get_image_file_name, verbose_name='Avatar thumbnail link'),
        ),
    ]
