# Generated by Django 4.2.9 on 2024-03-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0009_alter_administrator_thumbnail_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='creator',
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_administrators', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
            preserve_default=False,
        ),
    ]
