# Generated by Django 4.2.9 on 2024-03-03 02:13

import apps.api.administrator.utils
import apps.api.administrator.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0010_remove_administrator_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='administrator_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to=settings.AUTH_USER_MODEL, verbose_name='administrator creator'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='thumbnail_link',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.administrator.utils.get_image_file_name, validators=[apps.api.administrator.validators.validate_image_size], verbose_name='Avatar thumbnail link'),
        ),
    ]
