# Generated by Django 4.2.9 on 2024-03-04 13:00

import apps.api.administrator.utils
import apps.api.administrator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_administrator_administrator_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='thumbnail_link',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.administrator.utils.get_image_file_name, validators=[apps.api.administrator.validators.validate_image_size], verbose_name='avatar thumbnail link'),
        ),
    ]
