# Generated by Django 4.2.9 on 2024-03-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_alter_gender_creator'),
        ('country', '0004_alter_country_creator'),
        ('administrator', '0013_alter_administrator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='country.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='gender.gender', verbose_name='client gender'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='bibliography',
            field=models.TextField(default=1, max_length=500, verbose_name='bibliography'),
            preserve_default=False,
        ),
    ]
