# Generated by Django 4.2.9 on 2024-03-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0004_alter_gender_options_alter_gender_name'),
        ('administrator', '0014_administrator_address_administrator_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='bibliography',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='bibliography'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrator', to='gender.gender', verbose_name='Gender'),
        ),
    ]
