# Generated by Django 4.2.9 on 2024-02-28 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gender', '0002_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gender', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
