# Generated by Django 4.2.9 on 2024-03-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_alter_gender_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['name'], 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Gender'),
        ),
    ]
